language: node_js

node_js: "15.12.0"

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Site Update:`TZ=':Asia/Shanghai' date +' %Y-%m-%d %H:%m:%S'`"
  - git push --force --quiet "https://${token}@github.com/Lodour/Lodour.github.io.git" master:master

branches:
  only:
    - src

cache:
  directories:
    - node_modules
